# Generated by Django 3.2 on 2021-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_place_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='placedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.DateField(default=True)),
                ('img', models.ImageField(upload_to='picture')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
