# Generated by Django 3.2 on 2021-05-19 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_placedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedetails',
            name='months',
        ),
        migrations.AddField(
            model_name='placedetails',
            name='name',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placedetails',
            name='num',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
