# Generated by Django 3.2 on 2021-05-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_auto_20210519_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedetails',
            old_name='name',
            new_name='monthname',
        ),
        migrations.RenameField(
            model_name='placedetails',
            old_name='num',
            new_name='monthnum',
        ),
    ]
